apiVersion: v1
kind: Namespace
metadata:
  name: nginx-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aginx-2-deploy
  namespace: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2-svc
  namespace: nginx-2
  labels:
    app: nginx-2
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-2